### ISSUE TITLE
Find a font for English

### ISSUE THREAD

**Issue by masa47** [trans-farm/home#10]
Use Roboto font for English page (and alphabets appear in Japanese page as well)

**Comment by yoshicode** [comment]
https://saruwakakun.com/html-css/basic/font-family-how-to

**Comment by masa47** [comment]
https://fonts.google.com/specimen/Roboto?selection.family=Roboto

**Comment by masa47** [comment]
<link href="https://fonts.googleapis.com/css?family=M+PLUS+1p|Roboto&amp;subset=japanese" rel="stylesheet">
